DELETE Milestone Completed
nss-evening-cohort-14/michelin-star-restaurant-dashboard-michelin-star-restaurant-dashboard-1 pull request #51
Opened 2021-03-18 00:11 UTC by seancrossettie

## Description
Completed the DELETE milestone. When authenticated and logged in, user can delete items from menu, ingredients, staff, and reservations. The items delete on Firebase and the DOM is dynamically rendered after each item is deleted.

## Link to deployed app
https://development--michelin-star-restaurant.netlify.app/#

## Related Issue
https://github.com/nss-evening-cohort-14/michelin-star-restaurant-dashboard-michelin-star-restaurant-dashboard-1/issues/31
https://github.com/nss-evening-cohort-14/michelin-star-restaurant-dashboard-michelin-star-restaurant-dashboard-1/issues/29
https://github.com/nss-evening-cohort-14/michelin-star-restaurant-dashboard-michelin-star-restaurant-dashboard-1/issues/24
https://github.com/nss-evening-cohort-14/michelin-star-restaurant-dashboard-michelin-star-restaurant-dashboard-1/issues/23

## Motivation and Context
Required for MVP.

## How Can This Be Tested?
Fetch the branch
```
git fetch
git checkout development
```
Install and start webpack
```
npm install
npm start
```

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-03-18 00:15 UTC, TrinityChristiana commented on src/javascripts/components/navbar.js
> +        <a class="nav-link active" id="nav-menu" href="#">Menu</a>
Nice!

2021-03-18 00:19 UTC, drteresavasquez requested changes
On your delete reservations, there is a bug where the delete prompt shows twice if I logout and in again. Make sure you are removing the event listeners on log out. Make a ticket for that and keep moving forward.

GREAT JOB on the buttons not showing if the user is not logged in! It is a beautiful sight! 👍🏼

2021-03-18 00:19 UTC, drteresavasquez commented on src/javascripts/menu items/menuData.js
> +// CREATE MENU ITEMS
Is this code you plan to use? We do not like to see commented out code on the main/production branch, so remove this.

2021-03-18 00:43 UTC, TrinityChristiana requested changes
I see that there was a decision to move all the helper functions out of the helper folder. Let's move the API calls back. 

I also see the same was happening with the components folder. I won't block you all on moving the components over, but any function that returns HTML is a component and really should live there. Maybe while completing the next milestones that can be updated.

I also see some code that is for future milestones. Remember we don't want to work ahead. Let's remove that code out of here.

Anything prefixed with nit is not a blocker to getting this PR approved.

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/ingredients/ingredientsData.js
>  // API Calls for Ingredients
I didn't notice this before, but all of your API calls should live within the helper folder.

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/menu items/menu.js
> +      <button type="button" class="btn btn-secondary" id="edit-menu-item--${item.firebasekey}">Edit</button>
Remove this edit button. We don't want nonfunctional elements in the production. This is also considered working ahead.

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/menu items/menuData.js
API calls should live in the helper folder.

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/menu items/menuData.js
> +// CREATE MENU ITEMS
Remove this code. We don't want commented out code in production. This is also considered working ahead!

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/reservations/reservationData.js
> +import 'firebase/auth';
We want API calls to live in the helper's folder.

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/reservations/reservations.js
> +const showReservations = (array) => {
nit: This should really live in the components folder

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/reservations/reservations.js
> +    <button class="btn btn-info" data-toggle="modal" data-target="#formModal" id="edit-res-btn--${item.firebaseKey}">Edit Reservation</button>
Let's remove this Edit button. We don't want nonfunctional elements in the production. This is also considered working ahead.

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/staff/staffData.js
>  import axios from 'axios';
We want the API calls to live in the helpers folder

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/ingredients/showIngredients.js
> +const showUserIngredients = (array) => {
nit: The naming of this function is confusing. It reads as if the function returns ingredients that belong to a user.

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/menu items/forms/formModal.js
> +const formModal = (modalTitle) => {
nit: If you have a components folder, any function that just returns HTML should live within that folder. You can separate your components out by feature there.

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/menu items/menu.js
nit: Same with this file. It really should I've in the components folder.

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/menu items/menu.js
> +const showUserMenuItems = (array) => {
nit: The naming of this function is confusing. It reads as if the function returns menu items that belong to a user.

2021-03-18 00:43 UTC, TrinityChristiana commented on src/javascripts/reservations/reservations.js
> +const showUserReservations = (array) => {
nit: The naming of this function is confusing. It reads as if the function returns reservations that belong to a user.

2021-03-19 00:11 UTC, TrinityChristiana commented
Thank you for making the updates! I just need one more code change. It's not in the PR, but now that I'm testing the login state I see that the Staff page still has an Update button. Once that's updated I will get this PR approved for you all so that you can move on to the next milestone!

[Update button is here](https://github.com/nss-evening-cohort-14/michelin-star-restaurant-dashboard-michelin-star-restaurant-dashboard-1/blob/main/src/javascripts/components/showStaff.js#L18)

2021-03-19 00:27 UTC, TrinityChristiana approved these changes
Looks great! You all are approved to move on to the next milestone!

2021-03-19 00:29 UTC, elliewalkersm approved these changes

2021-03-19 00:56 UTC, drteresavasquez approved these changes

2021-03-19 00:57 UTC, merged